### ISSUE TITLE
libhoney crashes due to method not found in shaded Apache HTTP client

### ISSUE THREAD

**Issue by alamothe** [honeycombio/libhoney-java#107]
After running for some time, libhoney will crash with the following log:
```
21:31:48 SEVERE  Unexpected error. Batch request failed. An error has been published to the ResponseObservers for each event in the errored batch. 
Exception in thread "I/O dispatcher 1" java.lang.NoSuchMethodError: io.honeycomb.libhoney.shaded.org.apache.http.ConnectionClosedException: method <init>()V not found
	at io.honeycomb.libhoney.shaded.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
After that it will output to log every second or so:
```21:31:49 SEVERE  HTTP client rejected batch request. Error has been reported to ResponseObservers. 
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at io.honeycomb.libhoney.shaded.org.apache.http.util.Asserts.check(Asserts.java:46)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
	at io.honeycomb.libhoney.transport.batch.impl.HoneycombBatchConsumer.consume(HoneycombBatchConsumer.java:133)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.submitBatch(DefaultBatcher.java:217)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.handleTimeoutTriggers(DefaultBatcher.java:236)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.access$400(DefaultBatcher.java:36)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher$BatchingWorker.run(DefaultBatcher.java:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Looking at `io.honeycomb.libhoney.shaded.org.apache.http` it does look like the constructor is missing:
```java
package io.honeycomb.libhoney.shaded.org.apache.http;

import java.io.IOException;

public class ConnectionClosedException extends IOException {
    private static final long serialVersionUID = 617550366255636674L;

    public ConnectionClosedException(String message) {
        super(HttpException.clean(message));
    }
}
```
While in Apache HTTP client:
```java
package org.apache.http;

import java.io.IOException;

/**
 * Signals that the connection has been closed unexpectedly.
 *
 * @since 4.0
 */
public class ConnectionClosedException extends IOException {

    private static final long serialVersionUID = 617550366255636674L;

    /**
     * Creates a new ConnectionClosedException with the message "Connection is closed".
     *
     * @since 4.4.11
     */
    public ConnectionClosedException() {
        super("Connection is closed");
    }

    /**
     * Creates a new ConnectionClosedException with the specified detail message.
     *
     * @param message The exception detail message
     */
    public ConnectionClosedException(final String message) {
        super(HttpException.clean(message));
    }
```
Not sure what's going on.

**Versions**

- Java: `11.0.9`
- Libhoney: `1.4.0`

**Steps to reproduce**

1. Cannot be reproduced deterministically, however after some time the error will pop up.

**Additional context**

**Comment by JamieDanielson** [comment]
Thank you for raising this issue @alamothe , we're looking into it!

**Comment by JamieDanielson** [comment]
Thank you for the details @alamothe ! This has been updated and a [new release v1.4.1](https://github.com/honeycombio/libhoney-java/releases/tag/v1.4.1) is available
