### ISSUE TITLE
 libhoney-java is using old version of org.apache.httpcomponents:httpcore-nio causing it to crash the service

### ISSUE THREAD

**Issue by alamothe** [honeycombio/libhoney-java#96]
**Versions**

- Java: 11
- Libhoney: 1.3.1

**Steps to reproduce**

We log heavily from a single instance to Honeycomb. After a while, the CPU goes to 100% and the service is completely unresponsive. 

In the log we can find these:
```
I/O reactor terminated abnormally 
org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:359)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

We are already familiar with these errors, in fact our service uses Apache HTTP client async and was suffering from the same problem awhile ago. 

Additionally, there is a number of stacktraces like this:
```
HTTP client rejected batch request. Error has been reported to ResponseObservers. 
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at io.honeycomb.libhoney.shaded.org.apache.http.util.Asserts.check(Asserts.java:46)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
	at io.honeycomb.libhoney.shaded.org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
	at io.honeycomb.libhoney.transport.batch.impl.HoneycombBatchConsumer.consume(HoneycombBatchConsumer.java:133)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.submitBatch(DefaultBatcher.java:217)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.handleTimeoutTriggers(DefaultBatcher.java:236)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.access$400(DefaultBatcher.java:36)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher$BatchingWorker.run(DefaultBatcher.java:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Which points to Apache HTTP which is shaded by Libhoney. 

**Additional context**

There is a serious bug in `org.apache.httpcomponents:httpcore-nio:4.4.10` which is used by Libhoney. The bug is described here: https://issues.apache.org/jira/browse/HTTPASYNC-152

Fortunately, there is a simple solution.

This is fixed in `org.apache.httpcomponents:httpcore-nio:4.4.14`. However, since `org.apache.httpcomponents:httpasyncclient` has never been published with the bug, it needs to be specified as a dependency with the exact version for it to be used.

When can this be fixed and when can you release the new version? This is a serious issue as it crashes our service almost every day.

**Comment by alamothe** [comment]
Thank you!

**Comment by alamothe** [comment]
@MikeGoldsmith when will this be released?

EDIT: sorry to be pushy but we aren't logging anything to Honeycomb due to the bug and running blind for the last week

**Comment by alamothe** [comment]
@MikeGoldsmith any updates?

**Comment by emilyashley** [comment]
Looks like it's released :) https://github.com/honeycombio/libhoney-java/releases/tag/v1.4.0

**Comment by alamothe** [comment]
It's not published to Maven: https://mvnrepository.com/artifact/io.honeycomb.libhoney/libhoney-java

How do we update it?
